services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build: ./backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "4000:4000"
    depends_on:
      - db
  # volumes:
  #   - ./backend:/app
  frontend:
    build: ./frontend
    restart: always
    environment:
      - BACKEND_URL=http://backend:4000
    ports:
      - "3000:3000"
  # volumes:
  #   - ./frontend:/app
    depends_on:
      - backend
volumes:
  db_data:
